language: objective-c
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/travis-ci.mobileprovision.enc -d -a -out scripts/profile/travis-ci.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.end -d -a -out scripts/certs/dist.p12
- ./scripts/travis/add-key.sh
xcode_workspace: KegCop.xcworkspace
xcode_scheme: KegCop
xcode_sdk: iphonesimulator8.1
after_script:
- ./scripts/travis/remove-key.sh
env:
  global:
  - APP_NAME="KegCop"
  - 'DEVELOPER_NAME="iPhone Distribution: {your_name} ({code})"'
  - PROFILE_NAME="travis-ci"
  - secure: G4uyyzq6OJcriBfSo1aUkriunFYhvFYtvSkyS2iaODTUukyRR+actYyeBFOXagu0qletWd7Plx2fVtAvJ84FmpPe2jf4qJBEPpde8wvIOzoPYjc4eQQTo30J+UyO0rakENQYJCfaIFzauSWVBUuAiM1MRkfWJxJO5GVh7a/tzJI=


