language: objective-c
before_script:
- ./scripts/travis/add-key.sh
xcode_workspace: KegCop.xcworkspace
xcode_scheme: KegCop
xcode_sdk: iphonesimulator8.1
after_script:
- ./scripts/travis/remove-key.sh
env:
  global:
  - APP_NAME="KegCop"
  - 'DEVELOPER_NAME="iPhone Distribution: {your_name} ({code})"'
  - PROFILE_NAME="travis-ci"


